services:
  postgres:
    image: postgres:latest
    container_name: gym-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gymdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gymdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  gym-app:
    build: .
    container_name: gym-booking-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gymdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data: